// src/view/index.vue
<template>
    <div>
        <div class="page">
            <h1 class="page-title">Vue + Vue-Router + Vuex</h1>
            <nav class="page-nav">
                <router-link :to="item.path" active-class="active" exact v-for="item of routes" :key="item.path">{{ item.name }}</router-link>
            </nav>
        </div>
        <div>
            <router-view/>
        </div>
    </div>
</template>

<script>
export default {
  name: 'VueView',
  computed: {
    routes () {
      return this.$router.options.routes
    }
  }
}
</script>

<style lang="scss">
    @import "layout";
</style>

// src/view/index.tsx
import { hot } from 'react-hot-loader/root'
import React from 'react'
import { Provider } from 'react-redux'
import { BrowserRouter, NavLink, Switch, Route } from 'react-router-dom'
import { routes } from '../router'
import store from '../store'
import './layout.scss'

function View (props: any) {
  return (
    <Provider store={store}>
      <BrowserRouter>
        <div className="page">
          <h1 className="page-title">Typescript + React + React-Redux + React-Router</h1>
          <nav className="page-nav">
            {
              routes.map((route) => <NavLink activeClassName="active" exact={route.exact} to={route.path}
                                             key={route.path}>{route.name}</NavLink>)
            }
          </nav>
        </div>
        <div>
          <Switch>
            {
              routes.map((route) => <Route key={route.path} path={route.path} exact={route.exact}
                                           component={route.component}/>)
            }
          </Switch>
        </div>
      </BrowserRouter>
    </Provider>
  )
}

export default hot(View)
